package ch.qamwaq.ritomer.workpapers.application

const val DOCUMENT_RESOURCE_TYPE = "DOCUMENT"
const val DOCUMENT_CREATED_ACTION = "DOCUMENT.CREATED"
const val DOCUMENT_VERIFICATION_UPDATED_ACTION = "DOCUMENT.VERIFICATION_UPDATED"
