package ch.qamwaq.ritomer.workpapers.application

const val WORKPAPER_RESOURCE_TYPE = "WORKPAPER"
const val WORKPAPER_CREATED_ACTION = "WORKPAPER.CREATED"
const val WORKPAPER_UPDATED_ACTION = "WORKPAPER.UPDATED"
const val WORKPAPER_REVIEW_STATUS_CHANGED_ACTION = "WORKPAPER.REVIEW_STATUS_CHANGED"
