package ch.qamwaq.ritomer.mapping.application

const val MANUAL_MAPPING_RESOURCE_TYPE = "MANUAL_MAPPING"
const val MANUAL_MAPPING_CREATED_ACTION = "MANUAL_MAPPING.CREATED"
const val MANUAL_MAPPING_UPDATED_ACTION = "MANUAL_MAPPING.UPDATED"
const val MANUAL_MAPPING_DELETED_ACTION = "MANUAL_MAPPING.DELETED"
