spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

ritomer:
  security:
    jwt:
      hmac-secret: ${RITOMER_SECURITY_JWT_HMAC_SECRET}
  workpapers:
    documents:
      storage:
        backend: GCS
        gcs:
          bucket: ${RITOMER_WORKPAPERS_DOCUMENTS_STORAGE_GCS_BUCKET}
