package ch.qamwaq.ritomer.closing.application

const val CLOSING_FOLDER_RESOURCE_TYPE = "CLOSING_FOLDER"
const val CLOSING_FOLDER_CREATED_ACTION = "CLOSING_FOLDER.CREATED"
const val CLOSING_FOLDER_UPDATED_ACTION = "CLOSING_FOLDER.UPDATED"
const val CLOSING_FOLDER_ARCHIVED_ACTION = "CLOSING_FOLDER.ARCHIVED"
